#!/usr/bin/env python

#--- Option parsing ---#
"""
SIPSimR: simulate gradient fractionation of microbial community DNA (R code)

Usage:
  SIPSimR <command> [<args>...]
  SIPSimR -l | --list
  SIPSimR -h | --help
  SIPSimR --version

Options:
  -l --list     List subcommands.
  -h --help     Show this screen.
  --version     Show version.

Commands:
  Use the `list` option.
Description:
  Use this command to run R code associated with the SIPSim pipeline.
"""

import os, sys
from docopt import docopt
from subprocess import call

 # application                                                                
scriptDir = os.path.dirname(__file__)
libDir = os.path.join(scriptDir, 'lib')
sys.path.append(libDir)                                                       
import Utils

subcmdDir = os.path.join(scriptDir, 'lib', 'R')
 

if __name__ == '__main__':
    args = docopt(__doc__,
                  version='0.1',
                  options_first=True)

    # list subcommands
    if args['--list']:
        Utils.list_subcmds(subcmdDir, '.r', 'usage:')
        exit()

    # calling subcommand scripts
    scriptFile = os.path.join(subcmdDir, args['<command>'] + '.R')
    if not os.path.isfile(scriptFile):
        scriptFile = os.path.join(subcmdDir, args['<command>'] + '.r')
    
    if not os.path.isfile(scriptFile):
        msg = '"{}" is not a SIPSimR command. See "SIPSimR -h".'
        exit(msg.format(args['<command>']))
        
    exit(call(['Rscript', scriptFile] + args['<args>']))    
    
